---
# Thesee tasks deploy the Br4vo6ix C2

- name: Br4vo6ix | C2
  hosts: "{{ server_ip }}"
  vars:
    ansible_user: "{{ server_user }}"
    ansible_password: "{{ server_password }}"
    ansible_become_password: "{{ server_password }}"
  block:
    - name: Br4vo6ix | C2 | Make directory
      ansible.builtin.file:
        path: /br4vo6ix
        state: directory

    - name: Br4vo6ix | C2 | Copy server binary
      ansible.builtin.copy:
        src: br4vo6ix/out/server/server
        dest: /br4vo6ix/br4vo6ix

    - name: Br4vo6ix | C2 | Make quick-start script
      ansible.builtin.template:
        src: run-c2.sh
        dest: /br4vo6ix/run-c2.sh
        mode: 0744

    - name: Br4vo6ix | C2 | Copy frontend files
      ansible.builtin.copy:
        src: br4vo6ix/frontend/build
        dest: /br4vo6ix/build
        mode: 0444

    - name: Br4vo6ix | C2 | Install nginx
      ansible.builtin.package:
        name: nginx
        state: present

    - name: Br4vo6ix | C2 | Copy website Nginx config
      ansible.builtin.template:
        src: nginx.conf
        dest: /etc/nginx/sites-available/default
        mode: 0644
      notify:
        - Restart nginx

    - name: Br4vo6ix | C2 | Enable nginx
      ansible.builtin.service:
        name: nginx
        enabled: yes
